files:
  - source: /i18n/pot/*.pot
    ignore:
      - authorization_services__*
      - upgrading__*
      - server_development__*
      - server_admin__*
    translation: /i18n/po/%locale_with_underscore%/%file_name%.%locale_with_underscore%.po
