files:
  - source: /i18n/po/**/*.po
    ignore:
      - authorization_services__*
      - upgrading__*
      - server_development__*
      - server_admin__*
      - server_installation__*
      - securing_apps__*
    translation: /i18n/po/%locale_with_underscore%/%file_name%.po
