version: 2
jobs:
  clean:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-1e6c31274c4c49a6dbefa33293de692b67970d68

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: clean s3 for deleted branches
          command: |
            S3_BRANCHES=`aws s3 ls s3://keycloak-documentation/ | grep PRE | sed -e "s|.*PRE \(.*\)/.*|\1|"`
            GIT_BRANCHES=`git branch -r | sed -e "s|.* origin/||"` 

            echo "--- S3 Folders ---"
            echo "$S3_BRANCHES"
            echo "--- GIT Branches ---"
            echo "$GIT_BRANCHES"
            echo "--------------------"

            set +e

            for sb in ${S3_BRANCHES}; do
              echo "$GIT_BRANCHES" | grep "^${sb}$" > /dev/null
              if [ $? -ne 0 ] && [ -n "${sb}" ]; then
                echo "'${sb}' branch has already deleted, let's clean the s3 folder..."
                aws s3 rm s3://keycloak-documentation/${sb} --recursive
              fi
            done

  build:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-1e6c31274c4c49a6dbefa33293de692b67970d68

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx2024m
    
    steps:
      - checkout
      - run: git clone https://github.com/keycloak/keycloak-documentation.git source

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "source/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd source; mvn dependency:go-offline; cd ..;

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "source/pom.xml" }}
        
      # run build
      - run: ./build-translation.sh

      - store_artifacts:
          path: ~/repo/translated/dist/keycloak-documentation-i18n.zip

      - save_cache:
          paths:
            - ~/repo/translated/dist
            - ~/repo/site
          key: dist-{{ epoch }}

  deploy:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-1e6c31274c4c49a6dbefa33293de692b67970d68

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - dist-
      - run:
          name: deply to s3
          command: |
            aws s3 sync ~/repo/site/ s3://keycloak-documentation/
            aws s3 sync ~/repo/translated/dist/ s3://keycloak-documentation/$CIRCLE_BRANCH/ --delete


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - clean
      - build
      - deploy:
          requires:
            - build

