version: 2
jobs:
  clean:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-patch

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: clean s3 for deleted branches
          command: |
            S3_BRANCHES=`aws s3 ls s3://keycloak-documentation/ | grep PRE | sed -e "s|.*PRE \(.*\)/.*|\1|" | grep -v "^review$"`
            GIT_BRANCHES=`git branch -r | sed -e "s|.* origin/||"` 
            GIT_TAGS=`git ls-remote --tags | sed -e "s|.*refs/tags/\(.*\)|\1|"`

            echo "--- S3 Folders ---"
            echo "$S3_BRANCHES"
            echo "--- GIT Branches ---"
            echo "$GIT_BRANCHES"
            echo "--- GIT Tags ---"
            echo "$GIT_TAGS"
            echo "--------------------"

            set +e

            for sb in ${S3_BRANCHES}; do
              echo "$GIT_BRANCHES" | grep "^${sb}$" > /dev/null
              if [ $? -ne 0 ] && [ -n "${sb}" ]; then
                echo "'${sb}' branch has already been deleted, but let's check in tags before cleaning the s3 folder..."
                echo "$GIT_TAGS" | grep "^${sb}$" > /dev/null
                if [ $? -ne 0 ] && [ -n "${sb}" ]; then
                  echo "'${sb}' branch/tag has already been deleted, let's clean the s3 folder..."
                  aws s3 rm s3://keycloak-documentation/${sb} --recursive
                else
                  echo "'${sb}' exists as a tag, skip cleaning."
                fi
              else
                echo "'${sb}' exists as a branch, skip cleaning."
              fi
            done

  build:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-patch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx2024m
    
    steps:
      - checkout
      - run: git clone https://github.com/keycloak/keycloak-documentation.git source

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "source/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd source; mvn dependency:go-offline; cd ..;

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "source/pom.xml" }}
        
      # run build
      - run: ./build-translation.sh

      - store_artifacts:
          path: ~/repo/translated/dist/keycloak-documentation-i18n.zip

      - save_cache:
          paths:
            - ~/repo/translated/dist
            - ~/repo/site
            - ~/repo/settings.sh
          key: dist-{{ .Branch }}-{{ epoch }}

  deploy:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-patch

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - dist-{{ .Branch }}-
      - run:
          name: deply to s3
          command: |
            cp -r ~/repo/site/* ~/repo/translated/dist/

            VERSION=`grep "SOURCE_REVISION" ~/repo/settings.sh | cut -d "=" -f 2`
            sed -e "s|@VERSION@|$VERSION|g" ~/repo/site/index.html.tmpl > ~/repo/translated/dist/index.html

            rm ~/repo/translated/dist/index.html.tmpl
            rm ~/repo/site/index.html.tmpl

            [ "$CIRCLE_BRANCH" = "master" ] && aws s3 sync ~/repo/site/ s3://keycloak-documentation/
            [[ "$CIRCLE_BRANCH" = translate-* ]] && aws s3 sync ~/repo/translated/dist/ s3://keycloak-documentation/review/ --delete
            [[ "$CIRCLE_BRANCH" != translate-* ]] && aws s3 sync ~/repo/translated/dist/ s3://keycloak-documentation/$CIRCLE_BRANCH/ --delete
            echo "end"

  tag_deploy:
    docker:
      - image: openstandia/keycloak-documentation-i18n:po4a-patch

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - dist-{{ .Branch }}-
      - run:
          name: deply to s3
          command: |
            cp -r ~/repo/site/* ~/repo/translated/dist/

            VERSION=`grep "SOURCE_REVISION" ~/repo/settings.sh | cut -d "=" -f 2`
            sed -e "s|@VERSION@|$VERSION|g" ~/repo/site/index.html.tmpl > ~/repo/translated/dist/index.html

            rm ~/repo/translated/dist/index.html.tmpl
            rm ~/repo/site/index.html.tmpl

            aws s3 sync ~/repo/translated/dist/ s3://keycloak-documentation/$CIRCLE_TAG/ --delete
            echo "end"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - clean:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
      - tag_deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

